workdir: /group/zhougrp2/dguan/
ref: /group/zhougrp2/dguan/00_ref
reffa: /group/zhougrp2/dguan/00_ref/Gallus_gallus.GRCg6a.dna.toplevel.fa
gtf: /group/zhougrp2/dguan/00_ref/Gallus_gallus.GRCg6a.100.gtf
inra_gtf: /group/zhougrp2/dguan/00_ref/INRA_lncRNA/1_LNCextendedEns101.lncRNA.formated.gtf
chr: /group/zhougrp2/dguan/00_ref/chicken_chr.list
cdna: /group/zhougrp2/dguan/00_ref/Gallus_gallus.GRCg6a.cdna.all.fa
dbsnp: /group/zhougrp2/dguan/00_ref/gallus_gallus.vcf.gz
staridx: /group/zhougrp2/dguan/00_ref/staridx/
slmonidx: /group/zhougrp2/dguan/00_ref/salomidx/
map: /group/zhougrp2/dguan/13_indiv_gvcf/Chicken_GTEx_ALL_SAMPLES.map
chrlist: /group/zhougrp2/dguan/00_ref/Gallus_gallus.GRCg6a.interval.list
snakedir: /group/zhougrp2/dguan/99_scripts
sample_file: /group/zhougrp2/dguan/99_scripts/ase_samples.list
inra_samples: /group/zhougrp2/dguan/99_scripts/inra_ann_samples.tsv
intervals: /group/zhougrp2/dguan/99_scripts/Chicken_GTEx_intervals.list 
genome_chr: /group/zhougrp2/dguan/99_scripts/chicken_chr.list 
paired_reads: True
saf: /group/zhougrp2/dguan/00_ref/exon_quant/Gallus_gallus.GRCg6a.102.exon.saf
lncSAF: /group/zhougrp2/dguan/00_ref/INRA_lncRNA/1_LNCextendedEns101.lncRNA.saf
